package com.morningsun.app.presentation.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import com.morningsun.app.domain.model.LanguageMode

data class AppStrings(
    val appUser: String,
    val slogan: String,
    val navHome: String,
    val navHabits: String,
    val navCheckIn: String,
    val navDiary: String,
    val navProfile: String,
    val homeTitle: String,
    val homeSubtitle: String,
    val achievements: String,
    val statistics: String,
    val todaysHabits: String,
    val currentStreak: String,
    val days: String,
    val todaysProgress: String,
    val completed: String,
    val myHabits: String,
    val addHabit: String,
    val noHabits: String,
    val noHabitsSubtitle: String,
    val habitName: String,
    val category: String,
    val targetMinutes: String,
    val save: String,
    val cancel: String,
    val habitDetail: String,
    val habitNotFound: String,
    val todaysStatus: String,
    val notCheckedInYet: String,
    val loggedToday: String,
    val checkInTitle: String,
    val chooseHabit: String,
    val start: String,
    val stop: String,
    val selected: String,
    val diaryTitle: String,
    val addDiary: String,
    val noDiary: String,
    val noDiarySubtitle: String,
    val writeEntry: String,
    val diaryEntryTitle: String,
    val content: String,
    val mood: String,
    val tags: String,
    val diaryDetail: String,
    val diaryNotFound: String,
    val yearlyStatistics: String,
    val heatmap: String,
    val streak: String,
    val hours: String,
    val monthlySummary: String,
    val low: String,
    val high: String,
    val achievementsTitle: String,
    val achievementList: String,
    val unlocked: String,
    val keepGoing: String,
    val unlockedOn: String,
    val features: String,
    val reviewHeatmap: String,
    val seeMilestones: String,
    val cloudSync: String,
    val cloudSyncSubtitle: String,
    val exportData: String,
    val exportDataSubtitle: String,
    val settings: String,
    val settingsSubtitle: String,
    val appearance: String,
    val light: String,
    val dark: String,
    val language: String,
    val english: String,
    val chinese: String,
    val today: String,
    val habits: String,
    val minutesShort: String,
    val targetPerDay: String,
    val back: String,
    val profile: String,
    val categoryPosture: String,
    val categoryTrading: String,
    val categorySleep: String,
    val categoryExercise: String,
    val categoryReading: String
)

val LocalAppStrings = staticCompositionLocalOf { stringsFor(LanguageMode.EN) }

@Composable
fun appStrings(): AppStrings = LocalAppStrings.current

fun stringsFor(languageMode: LanguageMode): AppStrings = when (languageMode) {
    LanguageMode.EN -> enStrings
    LanguageMode.ZH -> zhStrings
}

private val enStrings = AppStrings(
    appUser = "MorningSun User",
    slogan = "Walk your way.",
    navHome = "Home",
    navHabits = "Habits",
    navCheckIn = "Check In",
    navDiary = "Diary",
    navProfile = "Profile",
    homeTitle = "Life is a long road.",
    homeSubtitle = "Walk it your way.",
    achievements = "Achievements",
    statistics = "Statistics",
    todaysHabits = "Today's Habits",
    currentStreak = "Current streak",
    days = "days",
    todaysProgress = "Today's Progress",
    completed = "Completed",
    myHabits = "My Habits",
    addHabit = "Add Habit",
    noHabits = "No habits yet",
    noHabitsSubtitle = "Create your first habit to start building momentum.",
    habitName = "Habit name",
    category = "Category",
    targetMinutes = "Target minutes",
    save = "Save",
    cancel = "Cancel",
    habitDetail = "Habit Detail",
    habitNotFound = "Habit not found",
    todaysStatus = "Today's Status",
    notCheckedInYet = "Not checked in yet",
    loggedToday = "Logged %d minutes today",
    checkInTitle = "Habit Check-in",
    chooseHabit = "Choose a habit",
    start = "Start",
    stop = "Stop",
    selected = "Selected",
    diaryTitle = "Growth Diary",
    addDiary = "Add diary",
    noDiary = "No diary entries yet",
    noDiarySubtitle = "Write down your progress, reflection, and ideas.",
    writeEntry = "Write Entry",
    diaryEntryTitle = "Title",
    content = "Content",
    mood = "Mood",
    tags = "Tags (comma separated)",
    diaryDetail = "Diary Detail",
    diaryNotFound = "Diary entry not found",
    yearlyStatistics = "Yearly Statistics",
    heatmap = "Heatmap",
    streak = "Streak",
    hours = "Hours",
    monthlySummary = "Monthly Summary",
    low = "Low",
    high = "High",
    achievementsTitle = "Achievements",
    achievementList = "Achievement List",
    unlocked = "Unlocked %d / %d",
    keepGoing = "Keep going, you are building consistency.",
    unlockedOn = "Unlocked on %s",
    features = "Features",
    reviewHeatmap = "Review your heatmap and trends",
    seeMilestones = "See the milestones you have unlocked",
    cloudSync = "Cloud Sync",
    cloudSyncSubtitle = "Sync stubs are ready for later integration",
    exportData = "Export Data",
    exportDataSubtitle = "Export data as Markdown or CSV",
    settings = "Settings",
    settingsSubtitle = "Theme and language",
    appearance = "Appearance",
    light = "Light",
    dark = "Dark",
    language = "Language",
    english = "English",
    chinese = "中文",
    today = "Today",
    habits = "Habits",
    minutesShort = "min",
    targetPerDay = "Target %d min / day",
    back = "Back",
    profile = "Profile",
    categoryPosture = "Posture",
    categoryTrading = "Trading",
    categorySleep = "Sleep",
    categoryExercise = "Exercise",
    categoryReading = "Reading"
)

private val zhStrings = AppStrings(
    appUser = "MorningSun 用户",
    slogan = "走你自己的路。",
    navHome = "首页",
    navHabits = "习惯",
    navCheckIn = "打卡",
    navDiary = "日记",
    navProfile = "我的",
    homeTitle = "人生路很长。",
    homeSubtitle = "走你自己的路。",
    achievements = "成就",
    statistics = "统计",
    todaysHabits = "今日习惯",
    currentStreak = "连续打卡",
    days = "天",
    todaysProgress = "今日进度",
    completed = "已完成",
    myHabits = "我的习惯",
    addHabit = "添加习惯",
    noHabits = "还没有习惯",
    noHabitsSubtitle = "创建第一个习惯，开始积累 momentum。",
    habitName = "习惯名称",
    category = "分类",
    targetMinutes = "目标分钟",
    save = "保存",
    cancel = "取消",
    habitDetail = "习惯详情",
    habitNotFound = "没有找到这个习惯",
    todaysStatus = "今日状态",
    notCheckedInYet = "今天还未打卡",
    loggedToday = "今天已记录 %d 分钟",
    checkInTitle = "习惯打卡",
    chooseHabit = "选择一个习惯",
    start = "开始",
    stop = "停止",
    selected = "已选择",
    diaryTitle = "成长日记",
    addDiary = "写日记",
    noDiary = "还没有日记",
    noDiarySubtitle = "记录你的进步、复盘和想法。",
    writeEntry = "写一篇",
    diaryEntryTitle = "标题",
    content = "内容",
    mood = "心情",
    tags = "标签（用逗号分隔）",
    diaryDetail = "日记详情",
    diaryNotFound = "没有找到这篇日记",
    yearlyStatistics = "年度统计",
    heatmap = "热力图",
    streak = "连续",
    hours = "小时",
    monthlySummary = "月度统计",
    low = "少",
    high = "多",
    achievementsTitle = "成就",
    achievementList = "成就列表",
    unlocked = "已解锁 %d / %d",
    keepGoing = "继续保持，你正在建立稳定的节奏。",
    unlockedOn = "解锁于 %s",
    features = "功能",
    reviewHeatmap = "查看习惯热力图和趋势",
    seeMilestones = "查看已经解锁的里程碑",
    cloudSync = "云端同步",
    cloudSyncSubtitle = "同步功能已预留，后续可接入",
    exportData = "导出数据",
    exportDataSubtitle = "导出为 Markdown 或 CSV",
    settings = "设置",
    settingsSubtitle = "主题和语言",
    appearance = "外观",
    light = "白天",
    dark = "黑夜",
    language = "语言",
    english = "English",
    chinese = "中文",
    today = "今日",
    habits = "习惯",
    minutesShort = "分钟",
    targetPerDay = "目标 %d 分钟 / 天",
    back = "返回",
    profile = "我的",
    categoryPosture = "体态",
    categoryTrading = "交易",
    categorySleep = "睡眠",
    categoryExercise = "锻炼",
    categoryReading = "阅读"
)
